Merge pull request #3 from FedorLuchkin/sprint_06
FedorLuchkin/yandex_ios_MovieQuiz pull request #3
Opened 2023-06-03 16:38 UTC by FedorLuchkin

networkClient creation

2023-06-04 11:25 UTC, IBDesignable requested changes

2023-06-04 11:25 UTC, IBDesignable commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
Обращу внимание на свойство `errorMessage`. 

Здесь может прийти текст с ошибкой, в таком случае сервис обычно возвращает пустой список фильмов `items`. 
С пустым списком приложение будет выглядеть сломанным. 
Это состояние называют краевым случаем, его стоит обрабатывать как ошибку, например, показывать алерт.
С точки зрения проектирования API сервиса IMDB, 
эту ошибку разработчики должны были вернуть c кодом ошибки клиента ([группа 4хх](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses)). 
Но случается и так, что ответ имеет статус код 200, а тело ответа содержит сообщение об ошибке, как в нашем примере. 
Такой ответ в любом случае необходимо обработать разработчику фронтенда (web, iOS, android).

 **Примеры состояний, когда такое происходит:**

- API key неверный
- API key просрочен
- количество запросов в день превышено (по документации не больше 100)

2023-06-04 11:25 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet private weak var activityIndicator: UIActivityIndicatorView!
очень хорошо что приватное свойство!

2023-06-04 11:25 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = false
Рекомендую посмотреть на свойство [hidesWhenStopped](https://developer.apple.com/documentation/uikit/uiactivityindicatorview/1622837-hideswhenstopped) 
у `activityIndicator`, и использовать его вместо ручного управления свойством `isHidden`. 

Когда ты будешь вызывать `startAnimating` – индикатор будет появляться автоматически, соответственно на `stopAnimating` – скрываться, а свойство `isHidden` больше не понадобится, индикатор все сделает за тебя. 

**Важно:** это свойство настраивают всего раз раз: кодом во `viewDidLoad()` или аналогичной галочкой у элемента на сториборде.
А строки `activityIndicator.isHidden = false(true)` нужно будет убрать

2023-06-04 11:25 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                self.questionFactory?.loadData()
Очень хорошо такой код выносить в отдельный метод! тогда в замыканиях нам становится чуточку проще работать, 
```suggestion
                self?.resetGame()
```
Во первых одной строчкой без разыменовывания self можно решить необходимую задачу. Во вторых, это помогает читаемости кода: разработчики всегда стремятся писать более плоский код(без глубоких табов). 
Чем короче вложенный код – тем лучше. 
Ну и в третьих – мы работаем над гибкостью и переиспользуемостью: возможно этот же кусочек повторяется при окончании игры, и его можно перевызвать. (а может нет, если там не нужно запрашивать вопросы заново)

2023-06-04 11:25 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        // questionFactory?.requestNextQuestion()
привыкай закомментаренный код удалять сразу. На ревью его уже не должно быть

2023-06-04 11:25 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionFactory?.loadData()
Замечу – что тут верный порядок: сначала даем пользователю понять что мы что-то крутим-вертим, затем запускаем под капотом процессы. Молодец!

2023-06-04 11:25 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionFactory?.requestNextQuestion()
Ты можешь дополнительно показывать `activityIndicator` между загрузкой вопросов, потому что загрузка вопроса тоже занимает некоторое время из-за получения изображения.
Перед запросом следующего вопроса – показывать индикатор, а в момент получения – выключать анимацию.

2023-06-04 11:25 UTC, IBDesignable commented on MovieQuiz/Services/QuestionFactory.swift
> +//            QuizQuestion(
Этот код больше не понадобится: можно смело удалить после апрува пул-реквеста)

2023-06-04 11:25 UTC, IBDesignable commented on MovieQuiz/Services/QuestionFactory.swift
> +    private var questionNumbers: [Int] = Array(0 ... 249).shuffled()
очень настороженно отношусь к магическим цифрам – почему именно 249? почему на 150? не 10?  
Разработчики про такое говорят – захардкодили – сделали приложение жестко завязанным на записанные в коде данные. 
Это не правильная стратегия

2023-06-04 11:25 UTC, IBDesignable commented on MovieQuiz/Services/QuestionFactory.swift
> +                print("Failed to load image")
Обращу внимание, что игра состоит из вопроса о рейтинге, на который отвечает пользователь, и контекста о фильме в виде постера(картинка). 
Без постера, пользователю будет затруднительно ответить на вопрос о рейтинге фильма верно.

В этом месте, функция не завершает свою работу и идет формировать вопрос без постера. 
В таком случае, бизнес-логика приложения будет нарушена, потому что пользователь не сможет ответить корректно, ведь изображения нет.
Это состояние стоит обработать, например, с помощью алерта. 
Не забудь, что алерт будет обновлять UI и это тоже нужно учесть (вернуть на main), ровно также, как и прерывание функции **(сделать return)**

2023-06-04 11:25 UTC, IBDesignable commented on MovieQuiz/Services/QuestionFactory.swift
> +        }
Не забывай что отступы важны и делают код читаемее: выдели участок и зажми control+i

2023-06-04 11:25 UTC, IBDesignable commented on MovieQuiz/Services/QuestionFactory.swift
> +                self.questionNumbers = Array(0 ... 249).shuffled()
я бы предложила тебе делать от 0 до movies.count

2023-06-04 11:25 UTC, IBDesignable commented on MovieQuiz/Services/QuestionFactory.swift
> +                self.questionNumbers = Array(0 ... 249).shuffled()
а при инициализации questionNumbers - не записывать туда этот массив.

2023-06-04 11:43 UTC, FedorLuchkin commented on MovieQuiz/Services/QuestionFactory.swift
> +                self.questionNumbers = Array(0 ... 249).shuffled()
Напишу тут мой коммент про шрифт кнопок: у меня в проекте прописан: YS Display Medium 20, так же как и в макете.

2023-06-05 14:23 UTC, IBDesignable commented on MovieQuiz/Services/QuestionFactory.swift
> +                self.questionNumbers = Array(0 ... 249).shuffled()
У кнопок да, должен быть medium 20, но почему-то при запуске был системный. 
И на сколько помню в прошлый раз у вопроса был меньше, чем 23й

2023-06-05 14:29 UTC, IBDesignable approved these changes
> У кнопок да, должен быть medium 20, но почему-то при запуске был системный.

<img width="579" alt="Снимок экрана 2023-06-05 в 17 27 16" src="https://github.com/FedorLuchkin/yandex_ios_MovieQuiz/assets/20269264/58e4c5a8-476a-4f8a-a106-8bff08f114ba">

Это можешь доправить самостоятельно! работу принимаю!

2023-06-05 14:29 UTC, IBDesignable commented on MovieQuiz/Services/QuestionFactory.swift
> +                        self.delegate?.didFailToLoadData(with: error)
хорошо!

2023-06-11 11:23 UTC, merged